### ISSUE TITLE
Written files not playable

### ISSUE THREAD

**Issue by steckes** [jmg049/wavers#26] opened 2024-09-20 15:56 UTC
Maybe connected to wrong RIFF size #24 ?

Version 1.4.3 from crates.io.

When I just read and write a wave file, the written file can't be played by any media player.

Code:

```
    use wavers::{write, Wav};
    let mut wav: Wav<f32> = Wav::from_path("test.wav").unwrap();

    let mut buffer = wav.read().unwrap();

    write("test.wav", &buffer, wav.sample_rate(), wav.n_channels()).unwrap();
```

**Comment by jmg049** [comment] 2024-09-20 23:12
I'll investigate this tomorrow and also look into the other issue and the pull request.

**Comment by jmg049** [comment] 2024-09-25 11:15
Sorry about the delay, real-world is busy. I have started investigating this and unfortunately not as simple as being caused the file size issue. It appears to be limited to just the float format, which thankfully narrows things down, but on the surface it is not clear what the cause is. Continuing to investigate

**Comment by steckes** [comment] 2024-09-25 11:55
Thank you for getting into it!
But good to know that the int16 format seems to work, I will try this instead!

**Comment by jmg049** [comment] 2024-12-29 17:01
I think the issue is fixed now. The issue seems to be stemming from the fact that some players/libraries for playing don't support the extensible format which Wavers used anytime the float type is used as per https://www.mmsp.ece.mcgill.ca/Documents/AudioFormats/WAVE/WAVE.html

But hey ¯\_(ツ)_/¯ 

Testing locally and the provided code produces a playable wav file

**Closed as completed by jmg049** 2024-12-29 17:01 UTC

**Comment by steckes** [comment] 2024-12-29 20:12
Interesting! Thanks for the fix :)

**Comment by jmg049** [comment] 2024-12-29 20:37
It is was is I suppose. The extensible format always confused me. The library can still read and write the extensible format just fine, but it will now always write f32 and f64 files as just the plain float format. 

Sorry for the delay with it :)
